package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-09-25T09:52:50.213+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebStockServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebStockServiceSoap {

    /**
     * 
     */
    @WebResult(name = "getCaiGouSortResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCaiGouSort", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCaiGouSort")
    @WebMethod(action = "http://tempuri.org/getCaiGouSort")
    @ResponseWrapper(localName = "getCaiGouSortResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCaiGouSortResponse")
    public org.tempuri.ArrayOfAdmin getCaiGouSort();

    @WebResult(name = "selectWidByUPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "selectWidByUPC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWidByUPC")
    @WebMethod(action = "http://tempuri.org/selectWidByUPC")
    @ResponseWrapper(localName = "selectWidByUPCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWidByUPCResponse")
    public int selectWidByUPC(
        @WebParam(name = "upc", targetNamespace = "http://tempuri.org/")
        java.lang.String upc
    );

    @RequestWrapper(localName = "GetManufacturerByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetManufacturerByWid")
    @WebMethod(operationName = "GetManufacturerByWid", action = "http://tempuri.org/GetManufacturerByWid")
    @ResponseWrapper(localName = "GetManufacturerByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetManufacturerByWidResponse")
    public void getManufacturerByWid(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "manufacturer", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> manufacturer,
        @WebParam(mode = WebParam.Mode.INOUT, name = "tel", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> tel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "site", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> site,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetManufacturerByWidResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> getManufacturerByWidResult
    );

    @WebResult(name = "GetWareInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfo")
    @WebMethod(operationName = "GetWareInfo", action = "http://tempuri.org/GetWareInfo")
    @ResponseWrapper(localName = "GetWareInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfoResponse")
    public org.tempuri.WareQita getWareInfo(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(name = "branchid", targetNamespace = "http://tempuri.org/")
        int branchid
    );

    @RequestWrapper(localName = "AddPackTask", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPackTask")
    @WebMethod(operationName = "AddPackTask", action = "http://tempuri.org/AddPackTask")
    @ResponseWrapper(localName = "AddPackTaskResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPackTaskResponse")
    public void addPackTask(
        @WebParam(name = "orderID", targetNamespace = "http://tempuri.org/")
        java.lang.String orderID,
        @WebParam(name = "pin", targetNamespace = "http://tempuri.org/")
        java.lang.String pin,
        @WebParam(name = "institution", targetNamespace = "http://tempuri.org/")
        int institution,
        @WebParam(name = "createUser", targetNamespace = "http://tempuri.org/")
        java.lang.String createUser,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mess", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> mess,
        @WebParam(mode = WebParam.Mode.OUT, name = "AddPackTaskResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> addPackTaskResult
    );

    @WebResult(name = "GetWareInfoByUPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareInfoByUPC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfoByUPC")
    @WebMethod(operationName = "GetWareInfoByUPC", action = "http://tempuri.org/GetWareInfoByUPC")
    @ResponseWrapper(localName = "GetWareInfoByUPCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfoByUPCResponse")
    public org.tempuri.ArrayOfWare getWareInfoByUPC(
        @WebParam(name = "upc", targetNamespace = "http://tempuri.org/")
        java.lang.String upc
    );

    @WebResult(name = "GetWareLWHResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareLWH", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareLWH")
    @WebMethod(operationName = "GetWareLWH", action = "http://tempuri.org/GetWareLWH")
    @ResponseWrapper(localName = "GetWareLWHResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareLWHResponse")
    public org.tempuri.WareQita getWareLWH(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @RequestWrapper(localName = "IsFitServiceWarenew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsFitServiceWarenew")
    @WebMethod(operationName = "IsFitServiceWarenew", action = "http://tempuri.org/IsFitServiceWarenew")
    @ResponseWrapper(localName = "IsFitServiceWarenewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsFitServiceWarenewResponse")
    public void isFitServiceWarenew(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "supplierNo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> supplierNo,
        @WebParam(mode = WebParam.Mode.INOUT, name = "supplierName", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> supplierName,
        @WebParam(mode = WebParam.Mode.INOUT, name = "tel", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> tel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "site", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> site,
        @WebParam(mode = WebParam.Mode.INOUT, name = "cat", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> cat,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Buyer", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> buyer,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Solder", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> solder,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Brand", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> brand,
        @WebParam(mode = WebParam.Mode.INOUT, name = "visitDays", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> visitDays,
        @WebParam(mode = WebParam.Mode.OUT, name = "IsFitServiceWarenewResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> isFitServiceWarenewResult
    );

    @WebResult(name = "selectWareInfoByWidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "selectWareInfoByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWareInfoByWid")
    @WebMethod(action = "http://tempuri.org/selectWareInfoByWid")
    @ResponseWrapper(localName = "selectWareInfoByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWareInfoByWidResponse")
    public org.tempuri.WareInfo selectWareInfoByWid(
        @WebParam(name = "rid", targetNamespace = "http://tempuri.org/")
        int rid,
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    /**
     * 
     */
    @WebResult(name = "GetWareSnSetByWidAndRightValueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareSnSetByWidAndRightValue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareSnSetByWidAndRightValue")
    @WebMethod(operationName = "GetWareSnSetByWidAndRightValue", action = "http://tempuri.org/GetWareSnSetByWidAndRightValue")
    @ResponseWrapper(localName = "GetWareSnSetByWidAndRightValueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareSnSetByWidAndRightValueResponse")
    public boolean getWareSnSetByWidAndRightValue(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(name = "rightValue", targetNamespace = "http://tempuri.org/")
        java.lang.String rightValue,
        @WebParam(name = "leftValue", targetNamespace = "http://tempuri.org/")
        java.lang.String leftValue
    );

    @WebResult(name = "GetWareInfoByWidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareInfoByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfoByWid")
    @WebMethod(operationName = "GetWareInfoByWid", action = "http://tempuri.org/GetWareInfoByWid")
    @ResponseWrapper(localName = "GetWareInfoByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareInfoByWidResponse")
    public java.lang.String getWareInfoByWid(
        @WebParam(name = "rid", targetNamespace = "http://tempuri.org/")
        int rid,
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "getWareStockResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWareStock", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareStock")
    @WebMethod(action = "http://tempuri.org/getWareStock")
    @ResponseWrapper(localName = "getWareStockResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareStockResponse")
    public int getWareStock(
        @WebParam(name = "rid", targetNamespace = "http://tempuri.org/")
        int rid,
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @RequestWrapper(localName = "GetImgNameWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetImgNameWid")
    @WebMethod(operationName = "GetImgNameWid", action = "http://tempuri.org/GetImgNameWid")
    @ResponseWrapper(localName = "GetImgNameWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetImgNameWidResponse")
    public void getImgNameWid(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        java.lang.String wid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "imageurl", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> imageurl,
        @WebParam(mode = WebParam.Mode.INOUT, name = "wname", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> wname,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetImgNameWidResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> getImgNameWidResult
    );

    @RequestWrapper(localName = "IsFitServiceWare", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsFitServiceWare")
    @WebMethod(operationName = "IsFitServiceWare", action = "http://tempuri.org/IsFitServiceWare")
    @ResponseWrapper(localName = "IsFitServiceWareResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsFitServiceWareResponse")
    public void isFitServiceWare(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "supplierNo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> supplierNo,
        @WebParam(mode = WebParam.Mode.INOUT, name = "supplierName", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> supplierName,
        @WebParam(mode = WebParam.Mode.INOUT, name = "tel", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> tel,
        @WebParam(mode = WebParam.Mode.INOUT, name = "site", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> site,
        @WebParam(mode = WebParam.Mode.OUT, name = "IsFitServiceWareResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> isFitServiceWareResult
    );

    @WebResult(name = "IsKillSoftWareResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsKillSoftWare", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsKillSoftWare")
    @WebMethod(operationName = "IsKillSoftWare", action = "http://tempuri.org/IsKillSoftWare")
    @ResponseWrapper(localName = "IsKillSoftWareResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsKillSoftWareResponse")
    public boolean isKillSoftWare(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "GetShelfInfoByWidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetShelfInfoByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetShelfInfoByWid")
    @WebMethod(operationName = "GetShelfInfoByWid", action = "http://tempuri.org/GetShelfInfoByWid")
    @ResponseWrapper(localName = "GetShelfInfoByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetShelfInfoByWidResponse")
    public org.tempuri.WareInfo getShelfInfoByWid(
        @WebParam(name = "rid", targetNamespace = "http://tempuri.org/")
        int rid,
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "GetIsSaleSlowWareResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIsSaleSlowWare", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsSaleSlowWare")
    @WebMethod(operationName = "GetIsSaleSlowWare", action = "http://tempuri.org/GetIsSaleSlowWare")
    @ResponseWrapper(localName = "GetIsSaleSlowWareResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsSaleSlowWareResponse")
    public java.lang.String getIsSaleSlowWare(
        @WebParam(name = "wids", targetNamespace = "http://tempuri.org/")
        java.lang.String wids
    );

    @WebResult(name = "GetCaiXiaoInfoByERPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCaiXiaoInfoByERPCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCaiXiaoInfoByERPCode")
    @WebMethod(operationName = "GetCaiXiaoInfoByERPCode", action = "http://tempuri.org/GetCaiXiaoInfoByERPCode")
    @ResponseWrapper(localName = "GetCaiXiaoInfoByERPCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCaiXiaoInfoByERPCodeResponse")
    public org.tempuri.CaiXiaoInfo getCaiXiaoInfoByERPCode(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        java.lang.String code
    );

    @WebResult(name = "GetSonAndOwnInfoByERPCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSonAndOwnInfoByERPCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSonAndOwnInfoByERPCode")
    @WebMethod(operationName = "GetSonAndOwnInfoByERPCode", action = "http://tempuri.org/GetSonAndOwnInfoByERPCode")
    @ResponseWrapper(localName = "GetSonAndOwnInfoByERPCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSonAndOwnInfoByERPCodeResponse")
    public org.tempuri.ArrayOfAdmin getSonAndOwnInfoByERPCode(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        java.lang.String code
    );

    @RequestWrapper(localName = "AddNewPackTask", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewPackTask")
    @WebMethod(operationName = "AddNewPackTask", action = "http://tempuri.org/AddNewPackTask")
    @ResponseWrapper(localName = "AddNewPackTaskResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewPackTaskResponse")
    public void addNewPackTask(
        @WebParam(name = "orderID", targetNamespace = "http://tempuri.org/")
        java.lang.String orderID,
        @WebParam(name = "pin", targetNamespace = "http://tempuri.org/")
        java.lang.String pin,
        @WebParam(name = "institution", targetNamespace = "http://tempuri.org/")
        int institution,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mess", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> mess,
        @WebParam(mode = WebParam.Mode.OUT, name = "AddNewPackTaskResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> addNewPackTaskResult
    );

    @RequestWrapper(localName = "AddNewWorkTask", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewWorkTask")
    @WebMethod(operationName = "AddNewWorkTask", action = "http://tempuri.org/AddNewWorkTask")
    @ResponseWrapper(localName = "AddNewWorkTaskResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewWorkTaskResponse")
    public void addNewWorkTask(
        @WebParam(name = "sourceUser", targetNamespace = "http://tempuri.org/")
        java.lang.String sourceUser,
        @WebParam(name = "sourceUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String sourceUserName,
        @WebParam(name = "pin", targetNamespace = "http://tempuri.org/")
        java.lang.String pin,
        @WebParam(name = "institution", targetNamespace = "http://tempuri.org/")
        int institution,
        @WebParam(name = "sourceDepartment", targetNamespace = "http://tempuri.org/")
        int sourceDepartment,
        @WebParam(name = "title", targetNamespace = "http://tempuri.org/")
        java.lang.String title,
        @WebParam(name = "contents", targetNamespace = "http://tempuri.org/")
        java.lang.String contents,
        @WebParam(name = "acceptInstitution", targetNamespace = "http://tempuri.org/")
        int acceptInstitution,
        @WebParam(name = "acceptDepartment", targetNamespace = "http://tempuri.org/")
        int acceptDepartment,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mess", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> mess,
        @WebParam(mode = WebParam.Mode.OUT, name = "AddNewWorkTaskResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> addNewWorkTaskResult
    );

    @WebResult(name = "getPackListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPackList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPackList")
    @WebMethod(action = "http://tempuri.org/getPackList")
    @ResponseWrapper(localName = "getPackListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPackListResponse")
    public java.lang.String getPackList(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    /**
     * 维护upc信息
     */
    @RequestWrapper(localName = "InsertWareUpc", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertWareUpc")
    @WebMethod(operationName = "InsertWareUpc", action = "http://tempuri.org/InsertWareUpc")
    @ResponseWrapper(localName = "InsertWareUpcResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertWareUpcResponse")
    public void insertWareUpc(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(name = "upc", targetNamespace = "http://tempuri.org/")
        java.lang.String upc
    );

    @WebResult(name = "getStockNumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getStockNum", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStockNum")
    @WebMethod(action = "http://tempuri.org/getStockNum")
    @ResponseWrapper(localName = "getStockNumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStockNumResponse")
    public java.lang.String getStockNum(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        java.lang.String wid
    );

    @WebResult(name = "getWareStock2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getWareStock2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareStock2")
    @WebMethod(action = "http://tempuri.org/getWareStock2")
    @ResponseWrapper(localName = "getWareStock2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetWareStock2Response")
    public org.tempuri.ArrayOfWareStock getWareStock2(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "selectWareInfoByShelfResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "selectWareInfoByShelf", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWareInfoByShelf")
    @WebMethod(action = "http://tempuri.org/selectWareInfoByShelf")
    @ResponseWrapper(localName = "selectWareInfoByShelfResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectWareInfoByShelfResponse")
    public org.tempuri.ArrayOfWareInfo selectWareInfoByShelf(
        @WebParam(name = "rid", targetNamespace = "http://tempuri.org/")
        int rid,
        @WebParam(name = "shelfNO", targetNamespace = "http://tempuri.org/")
        java.lang.String shelfNO
    );

    @WebResult(name = "GetIsPromotionWareResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIsPromotionWare", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsPromotionWare")
    @WebMethod(operationName = "GetIsPromotionWare", action = "http://tempuri.org/GetIsPromotionWare")
    @ResponseWrapper(localName = "GetIsPromotionWareResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsPromotionWareResponse")
    public java.lang.String getIsPromotionWare(
        @WebParam(name = "wids", targetNamespace = "http://tempuri.org/")
        java.lang.String wids
    );

    @RequestWrapper(localName = "GetCatBrandSnByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCatBrandSnByWid")
    @WebMethod(operationName = "GetCatBrandSnByWid", action = "http://tempuri.org/GetCatBrandSnByWid")
    @ResponseWrapper(localName = "GetCatBrandSnByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCatBrandSnByWidResponse")
    public void getCatBrandSnByWid(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid,
        @WebParam(mode = WebParam.Mode.INOUT, name = "snmin", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> snmin,
        @WebParam(mode = WebParam.Mode.INOUT, name = "snmax", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Integer> snmax,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetCatBrandSnByWidResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> getCatBrandSnByWidResult
    );

    /**
     * <span style='color:purple'></span>根据商品编号查询安装服务信息
     */
    @WebResult(name = "getSetFitServiceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSetFitService", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSetFitService")
    @WebMethod(action = "http://tempuri.org/getSetFitService")
    @ResponseWrapper(localName = "getSetFitServiceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSetFitServiceResponse")
    public org.tempuri.FitService getSetFitService(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "selectUPCbyWidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "selectUPCbyWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectUPCbyWid")
    @WebMethod(action = "http://tempuri.org/selectUPCbyWid")
    @ResponseWrapper(localName = "selectUPCbyWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SelectUPCbyWidResponse")
    public java.lang.String selectUPCbyWid(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "GetIsWrepriceByWidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIsWrepriceByWid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsWrepriceByWid")
    @WebMethod(operationName = "GetIsWrepriceByWid", action = "http://tempuri.org/GetIsWrepriceByWid")
    @ResponseWrapper(localName = "GetIsWrepriceByWidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIsWrepriceByWidResponse")
    public boolean getIsWrepriceByWid(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );

    @WebResult(name = "IsVWareResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsVWare", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsVWare")
    @WebMethod(operationName = "IsVWare", action = "http://tempuri.org/IsVWare")
    @ResponseWrapper(localName = "IsVWareResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsVWareResponse")
    public boolean isVWare(
        @WebParam(name = "wid", targetNamespace = "http://tempuri.org/")
        int wid
    );
}
