package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-09-25T09:52:50.313+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "WebStockService", 
                  wsdlLocation = "http://erp2.360buy.com/wzht/WebStockService.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class WebStockService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WebStockService");
    public final static QName WebStockServiceSoap12 = new QName("http://tempuri.org/", "WebStockServiceSoap12");
    public final static QName WebStockServiceSoap = new QName("http://tempuri.org/", "WebStockServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://erp2.360buy.com/wzht/WebStockService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebStockService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://erp2.360buy.com/wzht/WebStockService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WebStockService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebStockService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebStockService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public WebStockService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public WebStockService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public WebStockService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns WebStockServiceSoap
     */
    @WebEndpoint(name = "WebStockServiceSoap12")
    public WebStockServiceSoap getWebStockServiceSoap12() {
        return super.getPort(WebStockServiceSoap12, WebStockServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebStockServiceSoap
     */
    @WebEndpoint(name = "WebStockServiceSoap12")
    public WebStockServiceSoap getWebStockServiceSoap12(WebServiceFeature... features) {
        return super.getPort(WebStockServiceSoap12, WebStockServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WebStockServiceSoap
     */
    @WebEndpoint(name = "WebStockServiceSoap")
    public WebStockServiceSoap getWebStockServiceSoap() {
        return super.getPort(WebStockServiceSoap, WebStockServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebStockServiceSoap
     */
    @WebEndpoint(name = "WebStockServiceSoap")
    public WebStockServiceSoap getWebStockServiceSoap(WebServiceFeature... features) {
        return super.getPort(WebStockServiceSoap, WebStockServiceSoap.class, features);
    }

}
